services:

  postgres:
    image: postgres:17

    container_name: payment-postgres

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

  app:
    build: .

    container_name: payment-app

    ports:
      - "8090:8080"


    depends_on:
      - postgres

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}

      PAYPAL_OAUTH_URL: ${PAYPAL_OAUTH_URL}
      PAYPAL_CREATE_ORDER_URL: ${PAYPAL_CREATE_ORDER_URL}
      PAYPAL_CAPTURE_ORDER_URL: ${PAYPAL_CAPTURE_ORDER_URL}