spring:

  # =========================================
  # Application Config
  # =========================================
  application:
    name: payment-integration-service

  # =========================================
  # Flyway Database Migration Config
  # =========================================
  flyway:
    enabled: true                     # Enable Flyway database migrations
    locations: classpath:db/migration  # Look for SQL files in resources/db/migration/
    baseline-on-migrate: true         # Create baseline for existing databases (prevents errors)


  # =========================================
  # PostgreSQL Database Config
  # =========================================
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${SPRING_DATASOURCE_USERNAME:payments_user}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}



  # =========================================
  # JPA / Hibernate Config
  # =========================================
  jpa:
    hibernate:
      ddl-auto: validate   # Only validates schema matches entities, doesn't create tables,you can use none

    show-sql: true


# =========================================
# Server Config
# =========================================
server:
  port: 8080


# =========================================
# PayPal API Config
# =========================================
paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  oauth-url: ${PAYPAL_OAUTH_URL}
  create-order-url: ${PAYPAL_CREATE_ORDER_URL}
  capture-order-url: ${PAYPAL_CAPTURE_ORDER_URL}



# =========================================
# Logging Config
# =========================================
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

# =========================================
# JWT
# =========================================
jwt:
  secret: ${JWT_SECRET}


# =========================================
# App Users Config
# =========================================
app:
  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}
  user:
    username: ${APP_USER_USERNAME}
    password: ${APP_USER_PASSWORD}
