spring:
  application:
    name: payment-integration-service

  datasource:
    url: jdbc:mysql://localhost:3307/payment_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080


  paypal:
    client-id: ${PAYPAL_CLIENT_ID}
    client-secret: ${PAYPAL_CLIENT_SECRET}
    oauth-url: ${PAYPAL_OAUTH_URL}
    create-order-url: ${PAYPAL_CREATE_ORDER_URL}
    capture-order-url: ${PAYPAL_CAPTURE_ORDER_URL}
